env:
  es6: true
  node: true
extends:
  - "plugin:@typescript-eslint/recommended"
  - "@nuxtjs"
  - "plugin:nuxt/recommended"
  - "prettier"
  - "prettier/vue"
  - "prettier/@typescript-eslint"
  - "@vue/typescript"
  - "plugin:vue/essential"
  - "eslint:recommended"
parserOptions:
  ecmaVersion: 2018
  parser: "@typescript-eslint/parser"
plugins:
  - "prettier"
  - "@typescript-eslint"
rules:
  no-console: 0
