env:
  es6: true
  node: true
extends:
  - "eslint:recommended"
  - "@nuxtjs"
  - "plugin:nuxt/recommended"
  - "plugin:prettier/recommended"
  - "prettier"
  - "prettier/vue"
parserOptions:
  ecmaVersion: 2018
  parser: "babel-eslint"
plugins:
  - "prettier"
rules:
  no-console: 0
