env:
  es6: true
  node: true
extends:
  - "plugin:@typescript-eslint/recommended"
  - "@nuxtjs"
  - "plugin:nuxt/recommended"
  - "prettier"
  - "prettier/vue"
  - "prettier/@typescript-eslint"
parserOptions:
  ecmaVersion: 2018
  parser: "babel-eslint"
plugins:
  - "prettier"
